[project]
name = "mcp-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.2.0",
    "fastmcp>=2.4.0",
    "ruff>=0.11.11",
    "typing>=3.10.0.0",
]
